### ISSUE TITLE
this process does not work for individual accounts - there must be some extra magical steps that are missing

### ISSUE THREAD

**Issue by bwhittaker69** [dotnet/docs-maui#1677]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c41e4603-6e24-65df-1429-b6beff4d3ec8
* Version Independent ID: c41e4603-6e24-65df-1429-b6beff4d3ec8
* Content: [Apple account management - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/ios/apple-account-management?tabs=vs)
* Content Source: [docs/ios/apple-account-management.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/apple-account-management.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by bwhittaker69** [comment]
![image](https://github.com/dotnet/docs-maui/assets/24618423/c88c4a23-3fd4-4a01-bd1c-7a84d4cfec44)
![image](https://github.com/dotnet/docs-maui/assets/24618423/68e1c530-2c87-4328-91f2-b05f73b1e3b5)

i have dug into the error logs and this is what shows:

Xamarin.Messaging.Client.MessagingClient Error: 0 : An error occurred on client private2ceaa0bafb while executing a reply for topic xvs/idb/add-developer-account
Xamarin.Messaging.IDB.Contracts.AppleProvisioningException: Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
   at Xamarin.Messaging.IDB.AppleProvisioningManager.<GetUpdatedAccountAsync>d__13.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\AppleProvisioningManager.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.AppleProvisioningManager.<AddDeveloperAccountAsync>d__10.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\AppleProvisioningManager.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.Local.AddDeveloperAccountHandler.<ExecuteAsync>d__4.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\Handlers\AddDeveloperAccountHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.RequestHandler`2.<HandleAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\Handlers\RequestHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessageHandlerManager.<>c__DisplayClass16_1`2.<<RegisterHandlerAsync>b__2>d.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessageHandlerManager.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessagingClient.<ReplyAsync>d__32`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 0: 09/02/2023 17:37:10Z
    DateTime=2023-09-02T17:37:10.6799559Z: 09/02/2023 17:37:10Z

**Comment by davidbritch** [comment]
Hi @bwhittaker69 

Afraid there aren't any missing steps. I actually did this myself again yesterday and it worked fine for me. It's maybe that you've pasted in incorrect data into one of the fields. Failing that, it could be a product bug.

Looking at https://learn.microsoft.com/en-us/answers/questions/1099423/apple-developer-account-individual-error-there-was suggests there can be multiple reasons for the error occurring. Tying that in with your screenshot, it looks like you've entered in an email for your name, rather than your actual account name?
